name: Build Android 12 5.10 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git make gcc libssl-dev ncurses-dev \
          flex bison libelf-dev \
          gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

    - name: Install LLVM/Clang 15
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 15
        echo "/usr/lib/llvm-15/bin" >> $GITHUB_PATH

    - name: Clone kernel source
      run: |
        git clone https://android.googlesource.com/kernel/common \
          -b android12-5.10 \
          --depth=1 \
          --single-branch

    - name: Setup environment
      working-directory: ./common
      run: |
        # 配置编译参数
        export ARCH=arm64
        export LLVM=1
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export CROSS_COMPILE=aarch64-linux-gnu-
        
        # 创建编译输出目录
        mkdir -p out

    - name: Configure kernel
      working-directory: ./common
      run: |
        make O=out \
          ARCH=arm64 \
          LLVM=1 \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-gnu- \
          gki_defconfig

    - name: Build kernel
      working-directory: ./common
      run: |
        make O=out \
          ARCH=arm64 \
          LLVM=1 \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-gnu- \
          -j$(nproc) \
          Image.gz-dtb

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: |
          common/out/arch/arm64/boot/Image.gz-dtb
          common/out/.config
