name: Build Android 12 Kernel with Clang/LLVM

on:
  workflow_dispatch: # 支持手动触发

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev bc git wget lld

      - name: Clone Android 12 Kernel source
        run: |
          git clone https://android.googlesource.com/kernel/common -b android12-5.10 --depth=1 kernel
          cd kernel

      - name: Clone Clang/LLVM from GitLab
        run: |
          git clone https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone.git -b 12 clang
          export PATH=$(pwd)/clang/bin:$PATH

      - name: Check Clang and LLD
        run: |
          clang --version
          ld.lld --version

      - name: Configure kernel with defconfig
        run: |
          cd kernel
          make ARCH=arm64 CC=clang LD=ld.lld CROSS_COMPILE=aarch64-linux-gnu- defconfig

      - name: Build kernel
        run: |
          cd kernel
          make ARCH=arm64 CC=clang LD=ld.lld CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: Archive kernel image
        run: |
          cd kernel
          tar -czvf kernel-image.tar.gz arch/arm64/boot/Image

      - name: Upload kernel image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel/kernel-image.tar.gz
